### ISSUE TITLE
远程开锁

### ISSUE THREAD

**Issue by Carooot** [dogproton/SafeBaiyun#1]
老哥牛啊，感觉远程开锁也挺需要的，外卖就不用下楼了，可以实现不？

**Comment by honam** [comment]
+1 ，非常需要这个功能。另外这个离线软件，获取的mac和key会一直生效吗，还是说客户端没登出之前才有效？

**Comment by dogproton** [comment]
> 老哥牛啊，感觉远程开锁也挺需要的，外卖就不用下楼了，可以实现不？

走的蓝牙，所以远程就不用想了，不过我从阳台把手机伸出去是能开的。

> +1 ，非常需要这个功能。另外这个离线软件，获取的mac和key会一直生效吗，还是说客户端没登出之前才有效？

mac和key理论永久有效，跟登录状态没关系。
