### ISSUE TITLE
大佬能否讲下思路

### ISSUE THREAD

**Issue by Cloudplayer** [dogproton/SafeBaiyun#4]
大佬能否讲下思路和过程，有个类似的app，抓包获取了uuid，mac和key，蓝牙扫描获取了raw data，对蓝牙不怎么了解不知道怎么搞了😂

**Comment by wish007** [comment]
从db文件获取的mac地址应该是对单个门唯一不变的，那么假如蓝牙开门有效期到了不续费，这个key会不会失效？有效期内或过了有效期续费key会变吗？

**Comment by Today-ddr** [comment]
同求，研究了一段时间，看到回调函数，不知道蓝牙怎么取到什么值回来加密（也可能我理解错了），然后每次数值都不一样😫

**Comment by dogproton** [comment]
@Cloudplayer  我是直接逆向app搞的
@Today-ddr  大概流程就是就在UnlockRepo那里，你看一下蓝牙开发的文档，了解一下函数调用顺序你就知道了。

**Comment by Cloudplayer** [comment]
> 我是直接逆向app搞的 大概流程就是就在UnlockRepo那里，你看一下蓝牙开发的文档，了解一下函数调用顺序你就知道了。

好的👌，感谢大佬
